apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-nodeport
  labels:
    app: nginx-nodeport-demo
spec:
  type: NodePort
  selector:
    app: nginx-nodeport-demo # PAY ATTENTION TO THIS LABEL. IT IS USED TO MATCH THE PODS. NOT THE RS.
  ports:
    - name: http
      port: 80
      targetPort: 80